const C={Jedzenie:"🛒",Samochód:"⛽",Mieszkanie:"🏠",Zakupy:"🛍️",Rozrywka:"🎮",Praca:"💰",Zdrowie:"💊",Rachunki:"🧾",Inne:"💸"};const PT={Mieszkanie:"🏠",Internet:"🌐",Prąd:"⚡",Woda:"💧",Telefon:"📱",Kredyt:"🏦",Samochód:"🚗",Ubezpieczenie:"🛡️",Inne:"🧾"};const colors=["#397cff","#7650ff","#67e69a","#ffb84d","#ff6873","#55c7ff","#a979ff","#8993a5"];
let tx=JSON.parse(localStorage.getItem("mf_tx")||"[]"),budgets=JSON.parse(localStorage.getItem("mf_budgets")||"[]"),planned=JSON.parse(localStorage.getItem("mf_planned")||"[]"),profile=JSON.parse(localStorage.getItem("mf_profile")||"{}"),pinHash=localStorage.getItem("mf_pin_hash")||"",pinTries=0,selectedCat="Jedzenie",selectedBudgetCat="Jedzenie",type="expense",editing=null,statsDate=new Date();
const $=id=>document.getElementById(id),money=n=>Number(n).toLocaleString("pl-PL",{minimumFractionDigits:2,maximumFractionDigits:2})+" zł",short=n=>Number(n).toLocaleString("pl-PL",{maximumFractionDigits:0})+" zł",today=()=>new Date().toISOString().slice(0,10),fmt=d=>d?new Date(d+"T00:00:00").toLocaleDateString("pl-PL",{day:"numeric",month:"short",year:"numeric"}):"",esc=s=>{let d=document.createElement("div");d.textContent=s||"";return d.innerHTML},save=()=>{localStorage.setItem("mf_tx",JSON.stringify(tx));localStorage.setItem("mf_budgets",JSON.stringify(budgets));localStorage.setItem("mf_planned",JSON.stringify(planned))},monthName=d=>d.toLocaleDateString("pl-PL",{month:"long",year:"numeric"});
function totals(){return tx.reduce((a,x)=>{+x.amount&&(x.type==="income"?a.i+=+x.amount:a.e+=+x.amount);return a},{i:0,e:0})}
function navigate(n){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(n+"Screen").classList.add("active");document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.screen===n));$(".fab").style.display=n==="account"?"none":"block";if(n==="home")renderHome();if(n==="transactions")renderTransactions();if(n==="planned")renderPlanned();if(n==="budgets")renderBudgets();if(n==="stats")renderStats();if(n==="account")updateProfile()}
function renderHome(){let t=totals(),p=monthPlannedTotal();$("balance").textContent=money(t.i-t.e);$("income").textContent="+"+short(t.i);$("expense").textContent="-"+short(t.e);$("monthLabel").textContent=monthName(new Date());$("plannedTotal").textContent=short(p);$("forecastBalance").textContent=money(t.i-t.e-p);renderChart();renderRecent()}
function renderChart(){let days=[];for(let i=6;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);days.push(d)}let v=days.map(d=>tx.filter(x=>x.type==="expense"&&x.date===d.toISOString().slice(0,10)).reduce((s,x)=>s+ +x.amount,0)),m=Math.max(...v,1);$("chart").innerHTML=v.map(x=>`<div class="bar" style="height:${Math.max(5,x/m*100)}%"></div>`).join("");$("chartLabels").innerHTML=days.map(d=>`<span>${d.toLocaleDateString("pl-PL",{weekday:"short"}).slice(0,2)}</span>`).join("")}
function card(x){let inc=x.type==="income";return `<div class="transaction-wrap"><button class="transaction" data-id="${x.id}"><div class="transaction-icon">${x.icon||C[x.category]}</div><div class="transaction-main"><div class="transaction-name">${esc(x.name)}</div><div class="transaction-meta">${esc(x.category)} · ${fmt(x.date)}</div></div><div class="transaction-amount ${inc?"green":"red"}">${inc?"+":"-"}${short(x.amount)}</div></button><button class="delete" data-del="${x.id}">Usuń</button></div>`}
function attachSwipe(){document.querySelectorAll(".transaction").forEach(r=>{r.onclick=()=>alertTx(+r.dataset.id);let sx=0,cx=0;r.addEventListener("touchstart",e=>{sx=cx=e.touches[0].clientX;r.style.transition="none"},{passive:true});r.addEventListener("touchmove",e=>{cx=e.touches[0].clientX;r.style.transform=`translate3d(${Math.max(-85,Math.min(0,cx-sx))}px,0,0)`},{passive:true});r.addEventListener("touchend",()=>{r.style.transition="transform .3s cubic-bezier(.22,1,.36,1)";r.style.transform=`translate3d(${cx-sx<-40?-85:0}px,0,0)`})});document.querySelectorAll("[data-del]").forEach(b=>b.onclick=e=>{e.stopPropagation();tx=tx.filter(x=>x.id!==+b.dataset.del);save();refresh()})}
function renderRecent(){let l=[...tx].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,5);$("recent").innerHTML=l.length?l.map(card).join(""):`<div class="empty">💸<br>Brak transakcji</div>`;attachSwipe()}
function renderTransactions(){let q=($("search").value||"").toLowerCase(),t=totals();$("ti").textContent="+"+short(t.i);$("te").textContent="-"+short(t.e);let l=[...tx].sort((a,b)=>new Date(b.date)-new Date(a.date)).filter(x=>(x.name+" "+x.category+" "+(x.note||"")).toLowerCase().includes(q));$("transactions").innerHTML=l.length?l.map(card).join(""):`<div class="empty">🔎<br>Nic nie znaleziono</div>`;attachSwipe()}
function alertTx(id){let x=tx.find(a=>a.id===id);if(x)alert(`${x.name}\n${x.type==="income"?"+":"-"}${money(x.amount)}\n${x.category}\n${fmt(x.date)}${x.note?"\n"+x.note:""}`)}
function openTransaction(){editing=null;type="expense";selectedCat="Jedzenie";$("txTitle").textContent="Nowa transakcja";$("amount").value="";$("name").value="";$("date").value=today();$("note").value="";setType(type);renderCats();$("transactionModal").classList.add("show")}
function setType(v){type=v;$("expenseBtn").className=v==="expense"?"expense-on":"";$("incomeBtn").className=v==="income"?"income-on":""}
function renderCats(){$("categories").innerHTML=Object.entries(C).map(([n,i])=>`<button class="choice ${n===selectedCat?"selected":""}" data-cat="${n}"><span>${i}</span>${n}</button>`).join("");document.querySelectorAll("#categories [data-cat]").forEach(b=>b.onclick=()=>{selectedCat=b.dataset.cat;renderCats()})}
function saveTx(){let a=+$("amount").value,n=$("name").value.trim();if(!a||!n)return alert("Wpisz kwotę i nazwę.");tx.unshift({id:Date.now(),amount:a,name:n,date:$("date").value||today(),note:$("note").value.trim(),category:selectedCat,type,icon:C[selectedCat]});save();closeModal("transactionModal");refresh()}
function monthPlannedTotal(){let now=new Date(),ym=now.getFullYear()+"-"+String(now.getMonth()+1).padStart(2,"0");return planned.filter(p=>p.freq!=="once"||p.date.slice(0,7)===ym).reduce((s,p)=>s+ +p.amount,0)}
function daysUntil(d){return Math.ceil((new Date(d+"T00:00:00")-new Date(new Date().toDateString()))/86400000)}
function renderPlanned(){let total=monthPlannedTotal();$("plannedPageTotal").textContent=short(total);$("plannedCount").textContent=planned.length+" zobowiązań";$("plannedList").innerHTML=planned.length?planned.map(p=>{let days=daysUntil(p.date),cl=days<0?"overdue":days<=3?"due-soon":"",inst=p.leftInst?` · Pozostało ${p.leftInst}${p.totalInst?" z "+p.totalInst:""} rat`:"";return `<div class="planned-card"><div class="planned-card-top"><div class="planned-name"><div class="planned-icon">${PT[p.type]||"🧾"}</div><span>${esc(p.name)}</span></div><strong>${short(p.amount)}</strong></div><div class="planned-date ${cl}">${days<0?"⚠️ Po terminie":days===0?"🔔 Dzisiaj":`🔔 Za ${days} dni`} · ${fmt(p.date)}</div><div class="installments">${p.freq==="monthly"?"Co miesiąc":p.freq==="weekly"?"Co tydzień":p.freq==="2months"?"Co 2 miesiące":p.freq==="yearly"?"Co rok":"Jednorazowo"}${inst}</div></div>`}).join(""):`<div class="empty">📅<br>Brak planowanych płatności</div>`}
function openPlanned(){$("pName").value="";$("pAmount").value="";$("pDate").value=today();$("pTotalInst").value="";$("pLeftInst").value="";renderPlannedTypes();$("plannedModal").classList.add("show")}
function renderPlannedTypes(){$("plannedTypes").innerHTML=Object.entries(PT).map(([n,i])=>`<button class="choice ${$("pName").dataset.type===n?"selected":""}" onclick="selectPType('${n}',this)"><span>${i}</span>${n}</button>`).join("")}
function selectPType(n,b){$("pName").dataset.type=n;document.querySelectorAll("#plannedTypes .choice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}
function savePlanned(){let n=$("pName").value.trim(),a=+$("pAmount").value,d=$("pDate").value||today(),typ=$("pName").dataset.type||"Inne";if(!n||!a)return alert("Wpisz nazwę i kwotę.");planned.push({id:Date.now(),name:n,amount:a,date:d,freq:$("pFreq").value,reminder:+$("pReminder").value,type:typ,totalInst:+$("pTotalInst").value||0,leftInst:+$("pLeftInst").value||0});save();closeModal("plannedModal");renderPlanned();renderHome();scheduleLocalReminder(planned.at(-1))}
async function scheduleLocalReminder(p){if(!("Notification"in window))return;if(Notification.permission==="default")await Notification.requestPermission();if(Notification.permission!=="granted")return;/* PWA/web notifications require service worker/server for reliable future delivery. */}
function openBudget(){selectedBudgetCat="Jedzenie";$("budgetAmount").value="";renderBudgetCats();$("budgetModal").classList.add("show")}
function renderBudgetCats(){$("budgetCategories").innerHTML=Object.entries(C).map(([n,i])=>`<button class="choice ${n===selectedBudgetCat?"selected":""}" onclick="selectedBudgetCat='${n}';renderBudgetCats()"><span>${i}</span>${n}</button>`).join("")}
function saveBudget(){let a=+$("budgetAmount").value;if(!a)return alert("Wpisz limit.");let b=budgets.find(x=>x.category===selectedBudgetCat);b?b.amount=a:budgets.push({id:Date.now(),category:selectedBudgetCat,amount:a});save();closeModal("budgetModal");renderBudgets()}
function renderBudgets(){$("budgets").innerHTML=budgets.length?budgets.map(b=>{let s=tx.filter(x=>x.type==="expense"&&x.category===b.category).reduce((q,x)=>q+ +x.amount,0),p=Math.min(100,s/b.amount*100);return `<div class="budget-card"><div class="budget-top"><div class="budget-name"><div class="budget-icon">${C[b.category]}</div>${b.category}</div><div class="budget-number"><strong>${short(s)}</strong><small>z ${short(b.amount)}</small></div></div><div class="progress"><div class="progress-bar ${s>b.amount?"danger":""}" style="width:${p}%"></div></div><div class="budget-status ${s>b.amount?"danger":""}">${s>b.amount?"⚠️ Przekroczono":"Pozostało"} ${short(Math.abs(b.amount-s))}</div></div>`}).join(""):`<div class="empty">🎯<br>Brak budżetów</div>`}
function renderStats(){let y=statsDate.getFullYear(),m=statsDate.getMonth(),l=tx.filter(x=>{let d=new Date(x.date+"T00:00:00");return d.getFullYear()===y&&d.getMonth()===m&&x.type==="expense"}),map={};l.forEach(x=>map[x.category]=(map[x.category]||0)+ +x.amount);let c=Object.entries(map).sort((a,b)=>b[1]-a[1]),t=l.reduce((s,x)=>s+ +x.amount,0);$("statsMonth").textContent=monthName(statsDate);$("statsTotal").textContent=short(t);$("donutValue").textContent=short(t);$("statsCount").textContent=l.length+" transakcji";$("largest").textContent=c[0]?c[0][0]+" · "+short(c[0][1]):"Brak danych";let cur=0,parts=c.map(([n,v],i)=>{let a=cur,b=cur+v/t*360;cur=b;return `${colors[i%colors.length]} ${a}deg ${b}deg`});$("donut").style.background=t?`conic-gradient(${parts.join(",")})`:"#292f39";$("categoryList").innerHTML=c.map(([n,v],i)=>`<div class="category-row"><div class="category-row-top"><span>${C[n]} ${n}</span><strong>${short(v)} · ${(v/t*100).toFixed(0)}%</strong></div><div class="cat-progress"><div class="cat-fill" style="width:${v/t*100}%;background:${colors[i%colors.length]}"></div></div></div>`).join("")}
function changeStats(d){statsDate.setMonth(statsDate.getMonth()+d);renderStats()}
function openAccountEditor(){$("profileName").value=profile.name||"";$("profileEmail").value=profile.email||"";$("accountModal").classList.add("show")}
function saveProfile(){profile={name:$("profileName").value.trim()||"Moje konto",email:$("profileEmail").value.trim()||"Konto lokalne"};localStorage.setItem("mf_profile",JSON.stringify(profile));updateProfile();closeModal("accountModal")}
function updateProfile(){$("accountName").textContent=profile.name||"Moje konto";$("accountEmail").textContent=profile.email||"Konto lokalne";$("accountAvatar").textContent=(profile.name||"M")[0].toUpperCase();$("pinSettingText").textContent=pinHash?"Zmień blokadę PIN":"Ustaw blokadę PIN"}
async function hash(s){let b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function setupPin(){let p=prompt("Ustaw PIN 4–6 cyfr");if(!/^\d{4,6}$/.test(p||""))return alert("PIN musi mieć 4–6 cyfr.");let q=prompt("Powtórz PIN");if(p!==q)return alert("PIN-y są różne.");pinHash=await hash(p);localStorage.setItem("mf_pin_hash",pinHash);updateProfile();alert("PIN ustawiony.")}
async function unlockWithPin(){if(await hash($("pinInput").value)===pinHash){pinTries=0;$("pinInput").value="";$("lockScreen").classList.remove("show")}else{pinTries++;$("faceStatus").textContent="Nieprawidłowy PIN."}}
function pinInputChanged(){$("pinDots").textContent=("● ".repeat($("pinInput").value.length)).trim()||"○ ○ ○ ○ ○ ○"}
function lockApp(){if(!pinHash)return alert("Najpierw ustaw PIN.");$("lockScreen").classList.add("show");$("pinInput").focus()}
function setupFaceID(){if(!window.PublicKeyCredential)return alert("Passkeys/WebAuthn nie są dostępne w tej przeglądarce.");alert("Face ID będzie obsługiwane przez Passkey/WebAuthn. Do prawdziwego konta potrzebujemy jeszcze backendu.")}
function authenticateFace(){setupFaceID()}
function closeModal(id){$(id).classList.remove("show")}
document.querySelectorAll(".modal").forEach(m=>m.addEventListener("click",e=>{if(e.target===m)m.classList.remove("show")}));
function refresh(){renderHome();renderTransactions();renderPlanned();renderBudgets();renderStats();updateProfile()}
renderCats();renderBudgetCats();refresh();navigate("home");if(pinHash)lockApp();